name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature! Please provide as much detail as possible.
  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Explain the problem this feature solves.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe how the new feature should work.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any other approaches or existing workarounds?
    validations:
      required: false
